apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment0
  labels:
    app: myapp0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp0
  template:
    metadata:
      labels:
        app: myapp0
    spec:
      containers:
      - name: myapp0
        image: le999/app1:1.0
        ports:
        - containerPort: 3000
        env:
          - name: PORT
            value: "3000"
          - name: MONGO_URI
            value: mongodb://root:example@mongodb0:27017/mydb
          - name: KAFKA_URL
            value: kafka-release0-0.kafka-release0-headless.default.svc.cluster.local:9092
          - name: SAWTOOTH_VALIDATOR_URL
            value: tcp://sawtooth-0:4004
          - name: SAWTOOTH_REST_API_URL
            value: http://sawtooth-org0:8008
          - name: BACK_URL
            value: http://localhost:3000/api/
          - name: PUBLIC_KEY
            value: "-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDCUDXMn4PVqdm2V7QTEcanuPFY\nn8OMxM4jDGiByYjTjoBp+YIvJLciIyUgTltPcpGKutxUgwzMfuJ+uqAoGOkI6DWl\nIJwhbN0DCcEr/vI+LTo5L0XUF95I31mPa43hPpmjatAH76lOMW9VVI3iKrsKBLVS\nnXZxvqN64gECS0ACYQIDAQAB\n-----END PUBLIC KEY-----"
          - name: PRIVATE_KEY
            value: "-----BEGIN RSA PRIVATE KEY-----\nMIICXQIBAAKBgQDCUDXMn4PVqdm2V7QTEcanuPFYn8OMxM4jDGiByYjTjoBp+YIv\nJLciIyUgTltPcpGKutxUgwzMfuJ+uqAoGOkI6DWlIJwhbN0DCcEr/vI+LTo5L0XU\nF95I31mPa43hPpmjatAH76lOMW9VVI3iKrsKBLVSnXZxvqN64gECS0ACYQIDAQAB\nAoGARLKa8qcKswWDxSWosn08YJvQJ+cD+cayok2GvSwFRdZBrDXcQtKWNGl8fLl3\nKtV0gzmhH/fdFIdfiDJu4P49lJvIi4uOxYdWYsUdx3j9Kapg5D6MDSxTOu+hr/at\nmxuLkDz5mwsw7N6J12m4oXsrTMq4Z6kX7lkt74o2tpLLICkCQQD61vW3FFqMO1CO\n5F9X5k8L48CVGRURLmNUsGYcy0RncY3MkBp0lcWygm90yF6oEICbS9HjDSmGDRtT\nKybruWWbAkEAxk+OSXD1z7pbWtZL1mUGLtr2CLm7SZgPwrF5eTbexEzKdV75eI65\n7xWrHx/sbobT26/3up1ZnyORkCLnAHzVswJBAKUSAPFSO6Q9BG6Eaxn1Pd+dKYb0\n0qBT3ppE223ndkR8vcv4qPA//7HRlHdNxLzk3z1TT/QTHVhSF8FLjHljsDECQQCZ\n2DoQK3vnDTG2BK2Mw47KZr+cAUqUS01ewwPzz2d+bfxalbV/m2oPWoYIfWGUVTCi\nK59JvKw8UwGoCgufSzkVAkBpiI6xBM1k/QQWn2VvRS+FOiFYPcorbdrT+y3N4/PD\naam5oawrOKhBhVEE9j9GkRRa/Z+LM2ZM72XCyVAwqlsW\n-----END RSA PRIVATE KEY-----"
---

apiVersion: v1
kind: Service
metadata:
  name: myapp0
spec:
  type: ClusterIP
  selector:
    app: myapp0 
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000


---

apiVersion: v1
kind: Service
metadata:
  name: myapp0-lb
spec:
  selector:
    app: myapp0
  type: LoadBalancer
  ports:
    - name: "3000"
      port: 3000
      nodePort: 30001



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment1
  labels:
    app: myapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
      - name: myapp1
        image: le999/app1:1.0
        ports:
        - containerPort: 3000
        env:
          - name: PORT
            value: "3000"
          - name: MONGO_URI
            value: mongodb://root:example@mongodb1:27017/mydb
          - name: KAFKA_URL
            value: kafka-release1-0.kafka-release1-headless.default.svc.cluster.local:9092
          - name: SAWTOOTH_VALIDATOR_URL
            value: tcp://sawtooth-2:4004
          - name: SAWTOOTH_REST_API_URL
            value: http://sawtooth-org1:8008
          - name: BACK_URL
            value: http://localhost:3000/api/
          - name: PUBLIC_KEY
            value: "-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDCUDXMn4PVqdm2V7QTEcanuPFY\nn8OMxM4jDGiByYjTjoBp+YIvJLciIyUgTltPcpGKutxUgwzMfuJ+uqAoGOkI6DWl\nIJwhbN0DCcEr/vI+LTo5L0XUF95I31mPa43hPpmjatAH76lOMW9VVI3iKrsKBLVS\nnXZxvqN64gECS0ACYQIDAQAB\n-----END PUBLIC KEY-----"
          - name: PRIVATE_KEY
            value: "-----BEGIN RSA PRIVATE KEY-----\nMIICXQIBAAKBgQDCUDXMn4PVqdm2V7QTEcanuPFYn8OMxM4jDGiByYjTjoBp+YIv\nJLciIyUgTltPcpGKutxUgwzMfuJ+uqAoGOkI6DWlIJwhbN0DCcEr/vI+LTo5L0XU\nF95I31mPa43hPpmjatAH76lOMW9VVI3iKrsKBLVSnXZxvqN64gECS0ACYQIDAQAB\nAoGARLKa8qcKswWDxSWosn08YJvQJ+cD+cayok2GvSwFRdZBrDXcQtKWNGl8fLl3\nKtV0gzmhH/fdFIdfiDJu4P49lJvIi4uOxYdWYsUdx3j9Kapg5D6MDSxTOu+hr/at\nmxuLkDz5mwsw7N6J12m4oXsrTMq4Z6kX7lkt74o2tpLLICkCQQD61vW3FFqMO1CO\n5F9X5k8L48CVGRURLmNUsGYcy0RncY3MkBp0lcWygm90yF6oEICbS9HjDSmGDRtT\nKybruWWbAkEAxk+OSXD1z7pbWtZL1mUGLtr2CLm7SZgPwrF5eTbexEzKdV75eI65\n7xWrHx/sbobT26/3up1ZnyORkCLnAHzVswJBAKUSAPFSO6Q9BG6Eaxn1Pd+dKYb0\n0qBT3ppE223ndkR8vcv4qPA//7HRlHdNxLzk3z1TT/QTHVhSF8FLjHljsDECQQCZ\n2DoQK3vnDTG2BK2Mw47KZr+cAUqUS01ewwPzz2d+bfxalbV/m2oPWoYIfWGUVTCi\nK59JvKw8UwGoCgufSzkVAkBpiI6xBM1k/QQWn2VvRS+FOiFYPcorbdrT+y3N4/PD\naam5oawrOKhBhVEE9j9GkRRa/Z+LM2ZM72XCyVAwqlsW\n-----END RSA PRIVATE KEY-----"
---

apiVersion: v1
kind: Service
metadata:
  name: myapp1
spec:
  type: ClusterIP
  selector:
    app: myapp1 
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: myapp1-lb
spec:
  selector:
    app: myapp1
  type: LoadBalancer
  ports:
    - name: "3000"
      port: 3000
      nodePort: 30002