# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: ingress-kafka
#   annotations:
#     # use the shared ingress-nginx
#     kubernetes.io/ingress.class: "nginx"
#     nginx.ingress.kubernetes.io/rewrite-target: /
#     # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
#     # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
# spec:
#   rules:
#   - host: kafka-release
#     http:
#       paths:
#       - backend:
#           serviceName: kafka-release
#           servicePort: 9092

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: kafka-lb
# spec:
#   selector:
#     app.kubernetes.io/component: kafka
#     app.kubernetes.io/instance: kafka-release
#     app.kubernetes.io/name: kafka
#   ports:
#     - name: kfk-nodeport
#       port: 9092
#       nodePort: 30092
#     - name: kfk-nodeport2
#       port: 9093
#       nodePort: 30093
#   type: LoadBalancer

 
# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: kafka-lb2
# spec:
#   selector:
#     app.kubernetes.io/component: kafka
#     app.kubernetes.io/instance: kafka-release
#     app.kubernetes.io/name: kafka
#   ports:
#     - name: kfk-nodeport
#       port: 9092
#       nodePort: 30092
#   type: LoadBalancer
  
  
# kafka-release-0.kafka-release-headless.default.svc.cluster.local:9092
# ---


apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    app: app-pod

spec:
  containers:
    - name: app-container
      image: le999/app:1.0
      # ports:
      #   - containerPort: 6379
      env:
        - name: HOST_CONSUMER
          value: kafka-release.default.svc.cluster.local
        - name: HOST_PRODUCER
          value: kafka-release-0.kafka-release-headless.default.svc.cluster.local:9092


# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: zookeeper-0
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       name: zookeeper-0
#   template:
#     metadata:
#       labels:
#         name: zookeeper-0
#     spec:
#       containers:
#         - name: zookeeper
#           image: docker.io/bitnami/zookeeper:3-debian-10
#           ports:
#             - name: z-0
#               containerPort: 2181
#           # volumeMounts:
#           #   - name: z-mount
#           #     mountPath: /bitnami
#           env:
#             - name: ALLOW_ANONYMOUS_LOGIN
#               value: 'yes'

#       # volumes:
#       #   - name: z-mount
#       #     emptyDir: {}

# ---
# # apiVersion: v1
# # kind: Service
# # metadata:
# #   name: zookeeper-lb
# # spec:
# #   selector:
# #     name: zookeeper-0
# #   ports:
# #     - name: z-0
# #       port: 2181
# #       nodePort: 2183
# #   type: LoadBalancer

# # ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: zookeeper
# spec:
#   selector:
#     name: zookeeper-0
#   ports:
#     - name: z-0
#       port: 2181
#   type: ClusterIP


# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: kafka
# spec:
#   selector:
#     name: kafka-0
#   ports:
#     - name: k-0
#       port: 9092
#     - name: k-1
#       port: 9093
#   type: ClusterIP



# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: kafka-0
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       name: kafka-0
#   template:
#     metadata:
#       labels:
#         name: kafka-0
#     spec:
#       containers:
#         - name: kafka-0
#           image: docker.io/bitnami/kafka:2-debian-10
#           ports:
#             - name: k-port1
#               containerPort: 9092
#             - name: k-port2
#               containerPort: 9093
#           # volumeMounts:
#           #   - name: k-mount
#           #     mountPath: /bitnami
#           env:
#             - name: KAFKA_CFG_ZOOKEEPER_CONNECT
#               value: "zookeeper:2181"
#             - name: ALLOW_PLAINTEXT_LISTENER
#               value: "yes"
#             - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
#               value: "CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT"
#             - name: KAFKA_CFG_LISTENERS
#               value: "CLIENT://:9092,EXTERNAL://:9093"
#             - name: KAFKA_CFG_ADVERTISED_LISTENERS
#               value: "CLIENT://kafka:9092,EXTERNAL://localhost:9093"
#             - name: KAFKA_INTER_BROKER_LISTENER_NAME
#               value: "CLIENT"

      
#       # volumes:
#       #   - name: k-mount
#       #     emptyDir: {}

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: kafka-lb
# spec:
#   selector:
#     name: kafka-0
#   ports:
#     # - name: k-0
#     #   port: 9092
#     #   nodePort: 9092
#     - name: k-1
#       port: 9093
#       nodePort: 30093
#   type: LoadBalancer

