apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    app: app-pod

spec:
  containers:
    - name: app-container
      image: le999/app:1.0
      # ports:
      #   - containerPort: 6379
      env:
        - name: HOST_CONSUMER
          value: kafka-release.default.svc.cluster.local
        - name: HOST_PRODUCER
          value: kafka-release-0.kafka-release-headless.default.svc.cluster.local:9092


